---
name: Continuous Integration

on:
  workflow_call:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
    types:
      - synchronize
      - opened

jobs:
  ci:
    name: Continous Integration
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python3 -
          poetry install

      - name: Lint
        run: |
          poetry run flake8 .

      - name: Unit & BDD tests
        run: |
          poetry run coverage run --source=bpcalc -m pytest

      - name: Code coverage
        run: |
          poetry run coverage report --fail-under=80