---
name: Clean up

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**/*.md'
    types:
      - closed
  workflow_dispatch:
    workspace:
      description: 'Terraform workspace'
      required: true 
      type: string

env:
  IMAGE_NAME: bpcalc
  AWS_REGION: eu-west-1
  WORKSPACE: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || inputs.workspace }}

jobs:
  clean:
    name: Terraform clean
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
      
      - name: Destroy Infrastructure
        id: destroy
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG=sha-$SHORT_SHA
          terraform init
          terraform workspace select ${{ env.WORKSPACE }}
          terraform destroy -auto-approve \
          -var='image=${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}' \
          -var="tag=$TAG" \
          -var='region=${{ env.AWS_REGION }}'
          terraform workspace select default
          terraform workspace delete ${{ env.WORKSPACE }}
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}